language: ruby
rvm:
  - 2.3.3

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --empty-alt-ignore --disable-external ./_site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: '_site'
  fqdn: 'kateescott.com'
  on:
    branch: master

  # Temporarily fix deployment:
  # https://github.com/travis-ci/travis-ci/issues/9312#issuecomment-371951998
  edge:
    branch: pages-ivar-set
