on: push

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '~>2.6'
      - name: "Install Dependencies"
        run: |
          gem install bundler
          bundle install
      - name: "Jekyll Build"
        run: bundle exec jekyll build
      - name: 'HTML Proofer'
        run: |
          bundle exec htmlproofer --empty-alt-ignore --disable-external ./_site
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site/
          if-no-files-found: error
  deploy:
    name: "Deploy 🚀"
    runs-on: "ubuntu-latest"
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: site
          path: _site/
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
